if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    add_definitions(-DARMA_64BIT_WORD)
endif(CMAKE_SIZEOF_VOID_P EQUAL 8)

include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../3rdLibs/armadillo/armadillo-5.600.2/include)

if(WIN32)
    set(ARMA_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../3rdLibs/armadillo/armadillo-5.600.2/bin)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        if(MSVC14)		
            if(CMAKE_BUILD_TYPE MATCHES Release)			    
                target_link_libraries(${PROJECT_NAME} ${ARMA_PATH}/vc2015_x86_amd64/release/armadillo.lib)				
            else(CMAKE_BUILD_TYPE)
                message(FATAL_ERROR "only support release build by now")
            endif(CMAKE_BUILD_TYPE MATCHES Release)
        else(MSVC14)
            message(FATAL_ERROR "only support msvc14")
        endif(MSVC14)
    else(CMAKE_SIZEOF_VOID_P)
        message(FATAL_ERROR "only support 64bits")
    endif(CMAKE_SIZEOF_VOID_P EQUAL 8)
else(WIN32)
    message(FATAL_ERROR "do not support non windows platform yet")
endif(WIN32)
