include_directories(${CMAKE_CURRENT_LIST_DIR}/../3rdLibs/dlib/dlib-18.18)

if(WIN32)
    set(DLIB_PATH ${CMAKE_CURRENT_LIST_DIR}/../3rdLibs/dlib/dlib-18.18/bin)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        if(MSVC14)
            if(CMAKE_BUILD_TYPE MATCHES Release)
                target_link_libraries(${PROJECT_NAME} ${DLIB_PATH}/vc2015_x86_amd64/release/dlib.lib)
            endif(CMAKE_BUILD_TYPE MATCHES Release)

            if(CMAKE_BUILD_TYPE MATCHES Debug)
                target_link_libraries(${PROJECT_NAME} ${DLIB_PATH}/vc2015_x86_amd64/debug/dlib.lib)    
            endif(CMAKE_BUILD_TYPE MATCHES Debug)

        else(MSVC14)
            message(FATAL_ERROR "only support msvc14")
        endif(MSVC14)
    else(CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "only support 64bits")
    endif(CMAKE_SIZEOF_VOID_P EQUAL 8)
else(WIN32)
    message(FATAL_ERROR "do not support non windows platform yet")
endif(WIN32)
