CMAKE_MINIMUM_REQUIRED( VERSION 3.1 )

if(WIN32)
    set(LAPACK_PATH ${CMAKE_CURRENT_LIST_DIR}/../3rdLibs/lapack/lapack-3.5.0/bin)
    set(BLAS_PATH ${CMAKE_CURRENT_LIST_DIR}/../3rdLibs/openBlas/bin)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        if(MSVC14)
            if(CMAKE_BUILD_TYPE MATCHES Release)
                target_link_libraries(${PROJECT_NAME} ${BLAS_PATH}/x86_amd64/libopenblas.dll.a)
                target_link_libraries(${PROJECT_NAME} ${LAPACK_PATH}/vc2015_x86_amd64/release/liblapack.lib)
            else(CMAKE_BUILD_TYPE)
               message(FATAL_ERROR "only support release build by now")
            endif(CMAKE_BUILD_TYPE MATCHES Release)
        else(MSVC14)
            message(FATAL_ERROR "only support msvc14")
        endif(MSVC14)
    else(CMAKE_SIZEOF_VOID_P)
        message(FATAL_ERROR "only support 64bits")
    endif(CMAKE_SIZEOF_VOID_P EQUAL 8)
else(WIN32)
    message(FATAL_ERROR "do not support non windows platform yet")		
endif(WIN32)
